version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://hp49:root@cluster0.naf9odg.mongodb.net/leaderboard?retryWrites=true&w=majority&appName=Cluster0
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always